# Generated by Django 5.1.1 on 2024-09-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trust_Master",
            fields=[
                (
                    "Trust_Master_Id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Trust_Master_Name", models.CharField(max_length=225)),
                ("Trust_Master_Description", models.CharField(max_length=225)),
                ("Created_At", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
