# Generated by Django 5.1.1 on 2024-09-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trust_Value",
            fields=[
                ("Trust_Value_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Trust_Value_Name", models.CharField(max_length=225)),
                ("Trust_Value_Description", models.TextField(blank=True, null=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                (
                    "Trust_Master_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trust.trust_master",
                    ),
                ),
            ],
        ),
    ]
