# Generated by Django 5.1.1 on 2024-09-25 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0002_trust_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trust_master",
            old_name="Created_At",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="trust_master",
            old_name="Trust_Master_Description",
            new_name="trust_master_description",
        ),
        migrations.RenameField(
            model_name="trust_master",
            old_name="Trust_Master_Id",
            new_name="trust_master_id",
        ),
        migrations.RenameField(
            model_name="trust_master",
            old_name="Trust_Master_Name",
            new_name="trust_master_name",
        ),
        migrations.DeleteModel(
            name="Trust_Value",
        ),
    ]
