# Generated by Django 5.1.1 on 2024-09-28 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0008_alter_document_details_document_subtypes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document_details",
            old_name="document_subtypes",
            new_name="document_subtype",
        ),
    ]
