# Generated by Django 5.1.1 on 2024-10-18 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0021_meetingscheduler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingscheduler",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
