# Generated by Django 5.1.1 on 2024-11-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0022_alter_meetingscheduler_meeting_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingscheduler",
            name="is_proceeding",
            field=models.BooleanField(default=False),
        ),
    ]
