# Generated by Django 5.1.1 on 2024-09-27 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0003_rename_created_at_trust_master_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trust_Value",
            fields=[
                ("trust_value_id", models.AutoField(primary_key=True, serialize=False)),
                ("trust_value_name", models.CharField(max_length=225)),
                ("trust_value_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trust_master_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trust.trust_master",
                    ),
                ),
            ],
        ),
    ]
