# Generated by Django 5.1.1 on 2024-09-27 17:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0004_trust_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trust_Details",
            fields=[
                ("trust_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "trust_type",
                    models.CharField(
                        choices=[("type1", "TYPE1"), ("type2", "TYPE2")], max_length=50
                    ),
                ),
                (
                    "trust_nature",
                    models.CharField(
                        choices=[("nature1", "NATURE1"), ("nature2", "NATURE2")],
                        max_length=50,
                    ),
                ),
                ("trust_name", models.CharField(max_length=225)),
                ("trust_address", models.TextField()),
                ("trust_city", models.CharField(max_length=50)),
                (
                    "pincode",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Pincode must be a 6-digit number.",
                                regex="^\\d{6}$",
                            )
                        ],
                    ),
                ),
                ("trust_creation_date", models.DateField()),
                ("trust_govt_reg_no", models.CharField(max_length=100, unique=True)),
                (
                    "trust_website",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "trust_email_id",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("trust_description", models.TextField(blank=True, null=True)),
                (
                    "trust_contact_no",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone no.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
