# Generated by Django 5.1.1 on 2024-09-27 18:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0005_trust_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trustee_Details",
            fields=[
                ("trustee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "trustee_designation_vals",
                    models.CharField(
                        choices=[("pos1", "<pos_name>"), ("pos2", "<pos_name2>")],
                        max_length=100,
                    ),
                ),
                (
                    "trustee_manager_of",
                    models.CharField(
                        choices=[("manager1", "Manager 1"), ("manager2", "manager 2")],
                        max_length=50,
                    ),
                ),
                (
                    "trustee_class_of_person",
                    models.CharField(
                        choices=[("class1", "A"), ("class2", "B")], max_length=100
                    ),
                ),
                ("trustee_name", models.CharField(max_length=225)),
                (
                    "trustee_gender",
                    models.CharField(
                        choices=[("M", "MALE"), ("F", "FEMALE"), ("O", "OTHERS")],
                        max_length=10,
                    ),
                ),
                ("trustee_dob", models.DateField()),
                ("trustee_occupation", models.CharField(max_length=100)),
                ("trustee_address", models.TextField()),
                (
                    "trustee_email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "trustee_contact_no",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("trustee_trust_joining_date", models.DateField()),
                (
                    "trustee_status_values",
                    models.CharField(choices=[("status1", "A")], max_length=30),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trust_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trust.trust_details",
                    ),
                ),
            ],
        ),
    ]
