# Generated by Django 5.1.1 on 2024-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0007_document_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document_details",
            name="document_subtypes",
            field=models.CharField(
                choices=[("subtype1", "Subtype 1"), ("subtype2", "Subtype 2")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="document_details",
            name="document_type",
            field=models.CharField(
                choices=[("type1", "Type 1"), ("type2", "Type 2")], max_length=100
            ),
        ),
    ]
