# Generated by Django 5.1.1 on 2024-09-29 17:22

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0016_resolution"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resolution",
            old_name="mailing_temp_id",
            new_name="resolution_id",
        ),
        migrations.RenameField(
            model_name="resolution",
            old_name="mailing_temp_name",
            new_name="resolution_title",
        ),
        migrations.RenameField(
            model_name="resolution",
            old_name="mailing_temp_desc",
            new_name="resolutions_description",
        ),
        migrations.RemoveField(
            model_name="resolution",
            name="mailing_temp_attachment",
        ),
        migrations.RemoveField(
            model_name="resolution",
            name="template_for",
        ),
        migrations.AddField(
            model_name="resolution",
            name="resolution_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resolutions/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="resolution",
            name="resolution_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="resolution",
            name="resolution_type",
            field=models.CharField(
                choices=[("main", "Main"), ("supplement", "Supplement")],
                default="main",
                max_length=50,
            ),
        ),
    ]
