# Generated by Django 5.1.1 on 2024-10-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0018_master_mastervalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="trust_details",
            name="trust_state",
            field=models.CharField(
                choices=[("Maharashtra", "Maharashtra"), ("Delhi", "Delhi")],
                default=None,
                max_length=50,
            ),
        ),
    ]
