# Generated by Django 5.1.1 on 2024-10-09 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0019_trust_details_trust_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document_details",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="mailing_template",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="master",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="mastervalue",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="resolution",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="trust_details",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="trustee_details",
            name="created_by",
        ),
    ]
