# Generated by Django 5.1.1 on 2024-10-10 06:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0020_remove_document_details_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingScheduler",
            fields=[
                ("meeting_id", models.AutoField(primary_key=True, serialize=False)),
                ("meeting_title", models.CharField(default="Meet", max_length=150)),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=10,
                    ),
                ),
                (
                    "meeting_template",
                    models.CharField(
                        choices=[("temp1", "TEMP1"), ("temp2", "TEMP2")], max_length=50
                    ),
                ),
                ("meeting_time_date", models.DateField()),
                ("meeting_time_from", models.TimeField()),
                ("meeting_time_to", models.TimeField()),
                ("meeting_description", models.TextField(blank=True, null=True)),
                (
                    "meeting_link",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting_with",
                    models.ManyToManyField(
                        related_name="meetings", to="trust.trustee_details"
                    ),
                ),
                (
                    "trust",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trust.trust_details",
                    ),
                ),
            ],
        ),
    ]
